### ISSUE TITLE
"requests: alpha.kubernetes.io/nvidia-gpu: 1"  mapping values are not allowed in this context

### ISSUE THREAD

**Issue by jianzhangbjz** [Hui-Zhi/kubernetes#2]
Hi Hui-Zhi,

**Running Kubernetes locally via Docker, as this URL:http://kubernetes.io/docs/getting-started-guides/docker/  shows. I exec the following commands:**
```
docker run -d \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:rw \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --volume=/dev/:/dev/:rw \
    --net=host \
    --pid=host \
    --privileged \
    gcr.io/google_containers/hyperkube-amd64:v1.2.2 \
    /hyperkube kubelet \
        --containerized \
        --hostname-override=127.0.0.1 \
        --api-servers=http://localhost:8080 \
        --config=/etc/kubernetes/manifests \
        --allow-privileged \
        --v=2 \
        --experimental-nvidia-gpus=1 
```
But, it came error: **unknown flag: --experimental-nvidia-gpus**
I suppose this image(gcr.io/google_containers/hyperkube-amd64:v1.2.2) did not support the "--experimental-nvidia-gpus=1" command at present.
If so, how can I setting up a local cluster to test the GPU mapping?
Thanks a lot.

**Comment by jianzhangbjz** [comment]
I add "--experimental-nvidia-gpus=1" arguments into function of start_kubelet in /hack/local-up-cluster.sh, and the local cluster is running, the cluster info like below:
```
            "status": {
                "capacity": {
                    "alpha.kubernetes.io/nvidia-gpu": "1",
                    "cpu": "2",
                    "memory": "3884184Ki",
                    "pods": "110"
                },
                "allocatable": {
                    "alpha.kubernetes.io/nvidia-gpu": "1",
                    "cpu": "2",
                    "memory": "3884184Ki",
                    "pods": "110"
                },
```
It seems running normal for supporting GPU devices, but when I create Pod, it return error:
```
mapping values are not allowed in this context
```
the Yaml content as below:
```
apiVersion: v1
kind: Pod
metadata:
  name: jian-gpu
  namespace: default
spec:
  containers:
  - name: jian-gpu
    image: ubuntu_1404_x86_cuda:latest
    resources:
      requests: alpha.kubernetes.io/nvidia-gpu: 1
```

**Comment by jianzhangbjz** [comment]
seems the Pod YAML format error, it should be as below:
```
apiVersion: v1
kind: Pod
metadata:
  name: jian-gpu
  namespace: default
spec:
  containers:
  - name: jian-gpu
    image: ubuntu_1404_x86_cuda_jian:gpu
    resources:
      requests:
        alpha.kubernetes.io/nvidia-gpu: 1
```
But, it also got 'CrashLoopBackoff' status of Pod, as mentioned item 3 in [Error: "nvidiaGPU" is Invalid value](https://github.com/Hui-Zhi/kubernetes/issues/3), so closed it.
